# Generated by Django 4.1.1 on 2022-09-12 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("salary", models.IntegerField()),
                ("vacation_days", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Vacation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_mum", models.IntegerField()),
                ("name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("patronymic", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=50)),
                ("passport", models.CharField(max_length=50)),
                ("dob", models.DateField()),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.position"
                    ),
                ),
                (
                    "previous_positions",
                    models.ManyToManyField(
                        related_name="previous_positions", to="api.position"
                    ),
                ),
                (
                    "vacations",
                    models.ManyToManyField(related_name="vacations", to="api.vacation"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("abbreviation", models.CharField(max_length=100)),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manager",
                        to="api.employee",
                    ),
                ),
            ],
        ),
    ]
