# Generated by Django 4.1.1 on 2022-09-12 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_employee_email_department_employees_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="id_mum",
        ),
    ]
