# Generated by Django 4.1.1 on 2022-09-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_employee_id_mum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="employees",
            field=models.ManyToManyField(
                blank=True, default=None, related_name="employees", to="api.employee"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="previous_positions",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="previous_positions",
                to="api.position",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="vacations",
            field=models.ManyToManyField(
                blank=True, default=None, related_name="vacations", to="api.vacation"
            ),
        ),
    ]
